#!/bin/bash

#Copies something to a docker container where $1 is the local path $2 is a part of the container name and $3 is the path to move it to in the container
#E.g. to move a local version of utils into a container's node modules do dcp utils appContainer /home/src/app/node_modules
docker cp "$1" "$(dcid "$2")":"$3"
