#!/bin/zsh

TYPE=$1
INPUT_MESSAGE=$2
BRANCH=$(git branch --show-current | cat)


if [[ -z $INPUT_MESSAGE ]]; then
  echo "Please provide a message"
  exit 1
fi

# If ticket in message just commit
if [[ "$INPUT_MESSAGE" =~ [A-Z]+-[0-9]+ ]]; then
  FORMATTED_MESSAGE="$TYPE: $INPUT_MESSAGE"

  printf "Committing with message '%s'\n\n" "$FORMATTED_MESSAGE"
  git commit -m "$FORMATTED_MESSAGE" "${@:3}"
# Otherwise get the ticket ID from the branch and append it
elif [[ "$BRANCH" =~ [A-Z]+-[0-9]+ ]]; then
  TICKET=$(echo "$BRANCH" | grep -oE '[A-Z]+-[0-9]+')
  FORMATTED_MESSAGE="$TYPE: $INPUT_MESSAGE ($TICKET)"

  printf "Committing with message '%s'\n\n" "$FORMATTED_MESSAGE"
  git commit -m "$FORMATTED_MESSAGE" "${@:3}"
else
  FORMATTED_MESSAGE="$TYPE: $INPUT_MESSAGE"

  printf "Couldn't find JIRA ticket, committing with message '%s'\n\n" "$FORMATTED_MESSAGE"
  git commit -m "$FORMATTED_MESSAGE" "${@:3}"
fi

